# Spring Boot configuration
spring:
  profiles:
    active: test

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: TRACE

# Server configuration
server:
  port: 8080
  sessionTimeout: 30

#Environment variables GCP
gcp:
  project-id: "tracking-engine-290714"
  topic-topic_name: "tp-test"